# Generated by Django 4.1.2 on 2022-10-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='vote',
            field=models.CharField(choices=[('Likes', 'likes'), ('Unlike', 'unlike')], max_length=10, null=True),
        ),
    ]
